name: Basic Workflow

on: 
  push:
    branches:
      - main  # branch on which the trigger is applied
    paths:
     - 'src/**'
     - 'tests/**' #Only changes to these files will trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
        
      - name: Test
        run: echo "Testing"

      - name: Message
        run: echo "Welcome!"
      
      - name: Bye
        run: echo 'Bye Bye!'