name: combined workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * 1-5'

jobs:
  print:
    runs-on: ubuntu-latest
    env:
      CLIENT_NAME: ${{ secrets.CLIENT_NAME}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # (checks out code on runner, so we can run it)

      - name: print
        shell: bash
        run: |
          echo 'This is a combined workflow!'

      - name: Work Experience
        shell: bash
        run: |
          echo 'First company I have ever worked with is ${{ env.CLIENT_NAME }}'
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nothing.txt
          path: ./src/
