name: Cron type CI

on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: fedora
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
        
      - name: Run cron job
        shell: bash
        run: |
          echo 'Hello from Cron!'
      