name: MyWorkflow

on:  # trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: fedora
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Testing
        shell: bash
        run: |
          echo 'testing new trigger'
      - name: Greetings
        shell: bash
        run: |
          echo 'Hello, World!'
  deploy:
    runs-on: fedora
    needs: build  # this will wait until build step is completed, if this is not mentioned then the jobs can run parallely
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy
        shell: bash
        run: |
          echo 'I'm useless and I don't reploy anything'
